### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by star-andy** [YueGeQiu/nike_sneaker#1]

**Comment by star-andy** [comment]
![image](https://user-images.githubusercontent.com/15726024/34704963-e3721aa6-f537-11e7-9ce4-200020e882c5.png)

**Comment by star-andy** [comment]
![image](https://user-images.githubusercontent.com/15726024/34705051-761273ba-f538-11e7-83f3-6983bf39b87a.png)
这个位置的class_='js-card-link card-link d-sm-b'   改成这个

**Comment by fabregaszy** [comment]
感谢提醒。
可能是 Nike SNKRS 页面调整了。欢迎提交 PR。

**Comment by star-andy** [comment]
我以为这个是能帮忙抢的 就看了下  用nike的app一直提示错误 根本抽签都提交不了

**Comment by star-andy** [comment]
你改下代码把  我没fork 就一个字母  我就不提pr了 感谢开源

**Comment by fabregaszy** [comment]
@qinyang1018  好的，今天发 "The Ten" 是吧，是抽签形式的，不需要抢，祝好运。

**Comment by star-andy** [comment]
恩  但是抽签提交不上去 一直报错，连参与抽签的机会都不给
![4e68c105c7daa5cf97d8875e2c00d4ce](https://user-images.githubusercontent.com/15726024/34706753-7475b394-f544-11e7-87c7-d7601d41a1eb.png)
